spring:
  application:
    name: philstargram
  datasource:
    url: jdbc:postgresql://localhost:5432/philstargram
    username: philstargram
    password: philstargram
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  sql:
    init:
      mode: always
