-- member 모듈이 단독으로 소유하는 테이블. 다른 모듈은 이 테이블을 직접 조인해서는 안 된다.
CREATE TABLE IF NOT EXISTS members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    nickname    VARCHAR(50)  NOT NULL,
    bio         VARCHAR(500),
    created_at  TIMESTAMP    NOT NULL
);

-- post 모듈이 단독으로 소유하는 테이블. author_id 는 member id 에 대한 단순 참조값일 뿐
-- 외래 키/JPA 연관관계가 아니므로, post 는 member 테이블을 조인할 필요가 없다.
CREATE TABLE IF NOT EXISTS posts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id   BIGINT       NOT NULL,
    content     VARCHAR(2000) NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

-- follow 모듈이 단독으로 소유하는 테이블. follower_id/followee_id 는 member id 에 대한
-- 단순 참조값이며 외래 키가 아니다. "모듈 간 조인 금지" 규칙과 일관되게 유지한다.
CREATE TABLE IF NOT EXISTS follows (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id  BIGINT    NOT NULL,
    followee_id  BIGINT    NOT NULL,
    followed_at  TIMESTAMP NOT NULL,
    CONSTRAINT uq_follows_follower_followee UNIQUE (follower_id, followee_id)
);
-- feed 의 쓰기 시점 팬아웃을 지원한다: "이 작성자를 누가 팔로우하는가?"
CREATE INDEX IF NOT EXISTS idx_follows_followee_id ON follows (followee_id);

-- feed 모듈이 단독으로 소유하는 테이블: 사용자별로 미리 저장된(materialized) 타임라인.
-- post 가 PostCreatedEvent 를 발행할 때 쓰기 시점 팬아웃으로 채워진다.
-- author_nickname/content_preview 는 비정규화된 스냅샷으로, 피드 조회 시 member/post 를
-- 다시 호출할 필요가 없게 한다.
CREATE TABLE IF NOT EXISTS feed_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_member_id  BIGINT        NOT NULL,
    post_id          BIGINT        NOT NULL,
    author_id        BIGINT        NOT NULL,
    author_nickname  VARCHAR(50)   NOT NULL,
    content_preview  VARCHAR(200)  NOT NULL,
    created_at       TIMESTAMP     NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_feed_entries_owner_created_at ON feed_entries (owner_member_id, created_at DESC);

-- notification 모듈이 단독으로 소유하는 테이블. 오로지 PostCreatedEvent/MemberFollowedEvent
-- 에 반응하여 채워지며, 다른 모듈이 직접 호출하는 일은 없다.
CREATE TABLE IF NOT EXISTS notifications (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_member_id  BIGINT       NOT NULL,
    type                 VARCHAR(20)  NOT NULL,
    message              VARCHAR(500) NOT NULL,
    created_at           TIMESTAMP    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_recipient_created_at ON notifications (recipient_member_id, created_at DESC);
